name: Test my Docker skills
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Test Docker is available
        run: docker --version

      - name: Test I can run a container
        run: docker run hello-world
